apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: sample-dotnet-api-image
    newName: us-central1-docker.pkg.dev/your-gcp-project-id/sample-dotnet-repo/sample-dotnet-api
    newTag: initial
