apiVersion: v1
kind: Service
metadata:
  name: sample-dotnet-api-service
  namespace: default
  labels:
    app.kubernetes.io/name: sample-dotnet-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: sample-dotnet-api
